// components/Button.tsx
import { JSX } from "preact";
import { IS_BROWSER } from "$fresh/runtime.ts";

export default function Button(props: JSX.HTMLAttributes<HTMLButtonElement>) {
  return (
    <button
      {...props}
      disabled={!IS_BROWSER || props.disabled}
      class="w-36 border-2 border-[#000000] mx-auto py-2 px-4 font-semibold border-solid rounded shadow shadow-black/75 dark:shadow-white/60 dark:shadow-md transition-all ease-out"
    />
  );
}

// src/components/ui/Button.vue
<template>
  <button
    class="w-38 border-2 py-2 px-4 font-semibold border-solid rounded border-black dark:border-white shadow shadow-black/75 dark:shadow-white/60 dark:shadow-md transition-all ease-out"
  >
    {{ text }}
  </button>
</template>

<script>
export default {
  props: ['text'],
};
</script>
